const { defineConfig } = require("eslint/config");
const { FlatCompat } = require("@eslint/eslintrc");

const expoConfig = require("eslint-config-expo/flat");
const eslintPluginPrettierRecommended = require("eslint-plugin-prettier/recommended");
const eslintPluginTypescript = require("@typescript-eslint/eslint-plugin");
const eslintParserTypescript = require("@typescript-eslint/parser");

const compat = new FlatCompat({
  recommendedConfig: eslintPluginTypescript,
});

module.exports = defineConfig([
  expoConfig,
  compat.config(),
  {
    files: ["src/**/*.{ts,tsx}"],
    languageOptions: {
      parser: eslintParserTypescript,
      parserOptions: {
        project: ["./tsconfig.json"],
        sourceType: "module",
        tsconfigRootDir: __dirname,
      },
    },
    rules: {
      // js rules
      camelcase: ["error", { allow: ["unstable_settings"] }],
      "comma-spacing": "off",
      complexity: ["error", 20],
      "constructor-super": "error",
      curly: ["error", "all"],
      "default-param-last": "error",
      eqeqeq: "error",
      "id-length": [
        "error",
        {
          max: 30,
          min: 1,
        },
      ],
      "import/export": "error",
      "import/exports-last": "error",
      "import/first": "error",
      "import/group-exports": "error",
      "import/newline-after-import": "error",
      "import/no-cycle": "error",
      "import/no-duplicates": "error",
      "import/no-mutable-exports": "error",
      "import/no-named-as-default": "error",
      "import/no-named-as-default-member": "error",
      "import/no-useless-path-segments": "error",
      "max-classes-per-file": ["error", 1],
      "max-depth": ["error", 5],
      "max-lines": ["error", 200],
      "max-lines-per-function": ["error", 50],
      "no-cond-assign": "error",
      "no-const-assign": "error",
      "no-constant-condition": "error",
      "no-dupe-args": "error",
      "no-dupe-class-members": "error",
      "no-dupe-else-if": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-empty": "error",
      "no-empty-function": "error",
      "no-empty-pattern": "error",
      "no-ex-assign": "error",
      "no-fallthrough": "error",
      "no-func-assign": "error",
      "no-import-assign": "error",
      "no-inner-declarations": "error",
      "no-invalid-regexp": "error",
      "no-irregular-whitespace": "error",
      "no-loss-of-precision": "error",
      "no-misleading-character-class": "error",
      "no-nested-ternary": "error",
      "no-obj-calls": "error",
      "no-param-reassign": "error",
      "no-unexpected-multiline": "error",
      "no-unneeded-ternary": "error",
      "no-unreachable": "error",
      "no-unsafe-finally": "error",
      "no-unsafe-negation": "error",
      "no-unsafe-optional-chaining": "error",
      "no-unused-vars": "error",
      "no-useless-backreference": "error",
      "no-useless-rename": "error",
      "no-var": "error",
      "object-curly-spacing": [
        "error",
        "always",
        {
          arraysInObjects: true,
          objectsInObjects: true,
        },
      ],
      "sort-keys": ["error", "asc"],
      "sort-vars": ["error", { ignoreCase: true }],
      "spaced-comment": "error",
      "valid-typeof": "error",
      yoda: "error",
      "react/jsx-handler-names": "off",
      // typescript rules
      "@typescript-eslint/adjacent-overload-signatures": "error",
      "@typescript-eslint/array-type": "error",
      "@typescript-eslint/await-thenable": "error",
      "@typescript-eslint/ban-ts-comment": "error",
      "@typescript-eslint/consistent-indexed-object-style": ["error", "record"],
      "@typescript-eslint/consistent-type-assertions": "error",
      "@typescript-eslint/consistent-type-definitions": ["error", "interface"],
      "@typescript-eslint/consistent-type-exports": "error",
      "@typescript-eslint/consistent-type-imports": "error",
      "@typescript-eslint/explicit-function-return-type": "error",
      "@typescript-eslint/explicit-member-accessibility": "error",
      "@typescript-eslint/member-ordering": "error",
      "@typescript-eslint/method-signature-style": ["error", "property"],
      "@typescript-eslint/no-base-to-string": "error",
      "@typescript-eslint/no-confusing-void-expression": "error",
      "@typescript-eslint/no-empty-object-type": "error",
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-extra-non-null-assertion": "error",
      "@typescript-eslint/no-extraneous-class": "error",
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-for-in-array": "error",
      "@typescript-eslint/no-inferrable-types": "error",
      "@typescript-eslint/no-invalid-void-type": "error",
      "@typescript-eslint/no-meaningless-void-operator": "error",
      "@typescript-eslint/no-misused-promises": "error",
      "@typescript-eslint/no-namespace": "error",
      "@typescript-eslint/no-non-null-assertion": "error",
      "@typescript-eslint/no-redundant-type-constituents": "error",
      "@typescript-eslint/no-require-imports": "error",
      "@typescript-eslint/no-this-alias": "error",
      "@typescript-eslint/no-unnecessary-type-assertion": "error",
      "@typescript-eslint/no-unused-vars": "error",
      "@typescript-eslint/no-wrapper-object-types": "error",
      "@typescript-eslint/prefer-function-type": "error",
      "@typescript-eslint/prefer-nullish-coalescing": "error",
      "@typescript-eslint/prefer-optional-chain": "error",
      "@typescript-eslint/prefer-readonly": "error",
      "@typescript-eslint/prefer-reduce-type-parameter": "error",
      "@typescript-eslint/prefer-regexp-exec": "error",
      "@typescript-eslint/promise-function-async": "error",
      "@typescript-eslint/restrict-plus-operands": "error",
      "@typescript-eslint/restrict-template-expressions": "error",
      "@typescript-eslint/sort-type-constituents": "error",
      "@typescript-eslint/unbound-method": "error",
      "@typescript-eslint/unified-signatures": "error",
      "react/display-name": "error",
      "react/function-component-definition": ["error", { namedComponents: "arrow-function" }],
      "react/hook-use-state": "error",
      "react/jsx-boolean-value": ["error", "never"],
      "react/jsx-closing-bracket-location": "error",
      "react/jsx-curly-brace-presence": [
        "error",
        {
          children: "always",
          props: "always",
        },
      ],
      "react/jsx-fragments": ["error", "syntax"],
      "react/jsx-handler-names": "error",
      "react/jsx-key": "error",
      "react/jsx-max-depth": ["error", { max: 5 }],
      "react/jsx-no-comment-textnodes": "error",
      "react/jsx-no-duplicate-props": "error",
      "react/jsx-no-target-blank": "error",
      "react/jsx-no-useless-fragment": "error",
      "react/jsx-one-expression-per-line": ["error", { allow: "single-child" }],
      "react/jsx-sort-props": "error",
      "react/jsx-uses-vars": "error",
      "react/no-children-prop": "error",
      "react/no-deprecated": "error",
      "react/no-multi-comp": ["error", { ignoreStateless: false }],
      "react/no-unescaped-entities": "error",
      "react/prop-types": "error",
    },
  },
  {
    files: ["src/**/*.tsx"],
    rules: {
      "max-lines-per-function": ["error", 150],
    },
  },
  eslintPluginPrettierRecommended,
]);
